### ISSUE TITLE
jfreu.lite.php seems to be conflicting with jfreu.plugin.php

### ISSUE THREAD

**Issue by UncleEnk** [fanyx/docker-tmserver#8] opened 2024-06-16 18:02 UTC
Keep getting the following error whenever I try to run the server:

`trackmania_tmserver    | Fatal error: Cannot redeclare init_jfreu() (previously declared in /var/lib/xaseco/plugins/jfreu.lite.php:48) in /var/lib/xaseco/plugins/jfreu.plugin.php on line 283`
or in docker desktop:
![image](https://github.com/fanyx/docker-tmserver/assets/81113282/947ce325-4e2e-413b-b6be-9709413da552)
I have tried to blacklist jfreu.lite.php (though instructions unclear on how to blacklist, so it may not have come into effect). I have tried to delete jfreu.lite.php. But this error is just inescapable. 

The server keeps crashing, or restarting, or both, and I think this is why. Thanks for any help you can give.

**Comment by fanyx** [comment] 2024-06-17 20:32
what does your blacklist file look like?
it should look like this (assuming you want to disable jfreu.lite and keep the other two enabled):
```
jfreu.lite.php

```

maybe the blank line at the end is relevant, im not sure, i had some issues with it in the past that arent resolved tbh

that file should be mounted like in the example `docker-compose.yaml` i provided...

**Comment by fanyx** [comment] 2024-06-17 20:34
deleting the file from the running container wont do any good, as the `plugins.xml` file XAseco reads from gets created on container boot by the `xaseco/bin/plugins.sh` script

**Comment by UncleEnk** [comment] 2024-06-19 16:43
My blacklist.txt (should the file ending be txt, or should it be a binary?) file looks like what you showed. I'm not sure how I am supposed to mount it, I've just been doing `docker compose up -d` whenever I make a modification. I just un-deleted (not sure how I'm supposed to say that) the file. Thanks for the help btw.

Edit: Just deleted the docker image, then created it again so that it's up to date, still getting error.

**Comment by fanyx** [comment] 2024-06-19 17:08
oh yeah it's supposed to be without `.txt` (but a text file basically)
idk why i did things inconsistently

mount path has to be `/var/lib/xaseco/blacklist`

**Comment by UncleEnk** [comment] 2024-06-25 23:52
Is there any way to just remove the plugin? The blacklist isn't working at all for me.

**Comment by nbcraft** [comment] 2024-10-13 03:25
Having the same issue, this is what my `blacklist` looks like:
```
jfreu.chat.php
jfreu.lite.php
jfreu.plugin.php
plugin.rasp_irc.php
```
I've jumped into the container and confirmed `/var/lib/xaseco/blacklist` does look like that.

Funny enough, this only started happening after I added `plugin.rasp_irc.php` to the blacklist, which I did because I was getting spammed with this error (while my server was running) and didn't care for IRC:
```
****** Connecting to IRC *********   
[PHP Warning] fsockopen(): unable to connect to localhost:6667 (Address not available) on line 25 in file /var/lib/xaseco/plugins/plugin.rasp_irc.php
Could not connect to: localhost on port 6667        
```

So I did this in `blacklist`:
```
jfreu.chat.php
jfreu.plugin.php
plugin.rasp_irc.php
```
And this is when the `init_jfreu()` error started appearing.
So I added `jfreu.lite.php` to the `blacklist`, but that didn't help.
This is the error logs:

```
# initialize XASECO ###########################################################
[XAseco] PHP Version is 5.6.40 on Linux
[XAseco] Load settings [config.xml]
[XAseco] Load admin/ops lists [adminops.xml]
[XAseco] Load banned IPs list [bannedips.xml]
[XAseco] Load plugins list [plugins.xml]
[XAseco] Load plugin [plugin.localdatabase.php]
[XAseco] Load plugin [chat.admin.php]
[XAseco] Load plugin [chat.dedimania.php]
[XAseco] Load plugin [chat.help.php]
[XAseco] Load plugin [chat.laston.php]
[XAseco] Load plugin [chat.lastwin.php]
[XAseco] Load plugin [chat.me.php]
[XAseco] Load plugin [chat.players.php]
[XAseco] Load plugin [chat.players2.php]
[XAseco] Load plugin [chat.records.php]
[XAseco] Load plugin [chat.records2.php]
[XAseco] Load plugin [chat.recrels.php]
[XAseco] Load plugin [chat.server.php]
[XAseco] Load plugin [chat.songmod.php]
[XAseco] Load plugin [chat.stats.php]
[XAseco] Load plugin [chat.wins.php]
[XAseco] Load plugin [jfreu.chat.php]
[XAseco] Load plugin [jfreu.lite.php]
[XAseco] Load plugin [jfreu.plugin.php]

Fatal error: Cannot redeclare init_jfreu() (previously declared in /var/lib/xaseco/plugins/jfreu.lite.php:48) in /var/lib/xaseco/plugins/jfreu.plugin.php on line 283
```

Cheers

**Comment by nbcraft** [comment] 2024-10-13 04:01
I'm trying to debug this but I'm a bit confused, I'm not seeing a `plugins.xml` file anywhere in the repo, when it's mentioned in [the Xaseco docs](https://docs.xaseco.org/config-plugins.php) and is being loaded by the `loadPlugins()` function:

https://github.com/fanyx/docker-tmserver/blob/a8492ad00b4414c1bd863f25877bf7e73d41de66/xaseco/aseco.php#L670-L687

This function generates the `Load plugins list [plugins.xml]` log in my post above.

Am I missing something here or should this `plugins.xml` file be present somewhere?

**Comment by fanyx** [comment] 2024-10-13 07:08
the `plugins.xml` should get generated by https://github.com/fanyx/docker-tmserver/blob/master/xaseco/bin/plugins.sh on container startup as it's called during the entrypoint script
have you checked permissions on the blacklist file?
the script expects the file to be readable inside the container otherwise blacklist parsing is skipped
it doesnt throw an error on that tbf

it's been a hot minute since i touched the plugins code, i can look into this again
seems like a more common issue

**Comment by nbcraft** [comment] 2024-10-13 16:57
I think permissions are fine? Adding `plugin.rasp_irc.php` to `blacklist` did impact the behavior, and this is from within the container:

```
/ # cd /var/lib/xaseco                                                           
/var/lib/xaseco # ls -alh                                                        
total 664                                                                        
drwxr-xr-x    1 trackman trackman     510 Oct 13 16:44 .                         
drwxr-xr-x    1 root     root          54 Oct 11  2023 ..                        
lrwxrwxrwx    1 trackman trackman      13 Oct 13 16:44 @eaDir -> config/@eaDir   
-rw-r--r--    1 trackman trackman    2.7K Oct  4  2023 access.xml                
-rw-r--r--    1 trackman trackman    9.0K Oct  4  2023 adminops.xml              
-rw-r--r--    1 trackman trackman   87.8K Oct  4  2023 aseco.php                 
-rw-r--r--    1 trackman trackman     689 Oct  4  2023 autotime.xml              
-rw-r--r--    1 trackman trackman     123 Oct  4  2023 bannedips.xml             
drwxr-xr-x    1 trackman trackman      60 Oct  4  2023 bin                       
-rwxrwxr-x    1 trackman trackman      69 Oct 13 03:25 blacklist                 
drwxrwxr-x    1 trackman trackman      38 Oct 12 22:21 config                    
-rw-r--r--    1 trackman trackman   13.4K Oct 13 16:44 config.xml                
lrwxrwxrwx    1 trackman trackman      20 Oct 13 16:44 dedimania.xml -> config/dedimania.xml                                                                      
drwxr-xr-x    1 trackman trackman     688 Oct 11  2023 includes                  
-rw-r--r--    1 trackman trackman    1.2K Oct 13 16:44 localdatabase.xml         
drwxr-xr-x    1 trackman trackman      52 Oct  4  2023 localdb                   
-rw-r--r--    1 trackman trackman  479.3K Oct 13 16:44 logfile.txt               
-rw-r--r--    1 trackman trackman    5.0K Oct  4  2023 matchsave.xml             
-rw-r--r--    1 trackman trackman    3.1K Oct  4  2023 musicserver.xml           
-rw-r--r--    1 trackman trackman      55 Oct 13 03:18 musictagscache.xml        
drwxr-xr-x    1 trackman trackman    1.9K Oct  4  2023 panels                    
drwxr-xr-x    1 trackman trackman    1.6K Oct 13 03:08 plugins                   
drwxr-xr-x    1 trackman trackman    1.6K Oct 13 03:08 plugins                   
-rw-r--r--    1 trackman trackman    1.7K Oct 13 16:44 plugins.xml               
-rw-r--r--    1 trackman trackman    6.8K Oct  4  2023 rasp.settings.php         
-rw-r--r--    1 trackman trackman    7.8K Oct  4  2023 rasp.xml                  
drwxr-xr-x    1 trackman trackman     536 Oct  4  2023 styles                    
-rw-r--r--    1 trackman trackman     246 Oct  4  2023 text.tpl                  
/var/lib/xaseco # cat blacklist                                                  
jfreu.chat.php                                                                   
jfreu.lite.php                                                                   
jfreu.plugin.php                                                                 
plugin.rasp_irc.php
```

I see that `plugins.xml` got created there, here's the content of it:
```
/var/lib/xaseco # cat plugins.xml                                                
<?xml version="1.0" encoding="utf-8" ?>                                          
<aseco_plugins>                                                                  
  <plugin>plugin.localdatabase.php</plugin>                                      
  <plugin>chat.admin.php</plugin>                                                
  <plugin>chat.dedimania.php</plugin>                                            
  <plugin>chat.help.php</plugin>                                                 
  <plugin>chat.laston.php</plugin>                                               
  <plugin>chat.lastwin.php</plugin>                                              
  <plugin>chat.me.php</plugin>                                                   
  <plugin>chat.players.php</plugin>                                              
  <plugin>chat.players2.php</plugin>                                             
  <plugin>chat.records.php</plugin>                                              
  <plugin>chat.records2.php</plugin>                                             
  <plugin>chat.recrels.php</plugin>                                              
  <plugin>chat.server.php</plugin>                                               
  <plugin>chat.songmod.php</plugin>                                              
  <plugin>chat.stats.php</plugin>                                                
  <plugin>chat.wins.php</plugin>                                                 
  <plugin>jfreu.chat.php</plugin>                                                
  <plugin>jfreu.lite.php</plugin>                                                
  <plugin>jfreu.plugin.php</plugin>                                              
  <plugin>mistral.idlekick.php</plugin>                                          
  <plugin>plugin.access.php</plugin>                                             
  <plugin>plugin.autotime.php</plugin>                                           
  <plugin>plugin.chatlog.php</plugin>                                            
  <plugin>plugin.checkpoints.php</plugin>                                        
  <plugin>plugin.dedimania.php</plugin>                                          
  <plugin>plugin.donate.php</plugin>                                             
  <plugin>plugin.matchsave.php</plugin>                                          
  <plugin>plugin.ml_howto.php</plugin>                                           
  <plugin>plugin.msglog.php</plugin>                                             
  <plugin>plugin.musicserver.php</plugin>                                        
  <plugin>plugin.muting.php</plugin>                                             
  <plugin>plugin.panels.php</plugin>                                             
  <plugin>plugin.rasp.php</plugin>                                               
  <plugin>plugin.rasp_chat.php</plugin>                                          
  <plugin>plugin.rasp_jukebox.php</plugin>                                       
  <plugin>plugin.rasp_karma.php</plugin>                                         
  <plugin>plugin.rasp_nextmap.php</plugin>                                       
  <plugin>plugin.rasp_nextrank.php</plugin>                                      
  <plugin>plugin.rasp_votes.php</plugin>                                         
  <plugin>plugin.rounds.php</plugin>                                             
  <plugin>plugin.rpoints.php</plugin>                                            
  <plugin>plugin.style.php</plugin>                                              
  <plugin>plugin.tmxinfo.php</plugin>                                            
  <plugin>plugin.track.php</plugin>                                              
  <plugin>plugin.uptodate.php</plugin>                                           
</aseco_plugins>
```

`plugin.rasp_irc.php` is indeed not in there, but all the `jfreu` stuff is 🤔 

Thanks for your help and for putting together this project 🙏

**Comment by nbcraft** [comment] 2024-10-13 18:00
Okay, I've been digging a bit more and I think I found the issue.

As a reminder this is my `blacklist`:
```
jfreu.chat.php                                                                   
jfreu.lite.php                                                                   
jfreu.plugin.php                                                                 
plugin.rasp_irc.php
```

I looked into the `xaseco/bin/plugins.sh` script and while trying to reproduce manually within the container, I ran:
```
PLUGINS_LIST=($(ls -d plugins/*.php | sed -e 's/plugins\///g'))
echo ${PLUGINS_LIST[@]} | tr ' ' '\n' | grep -vFf blacklist
```

The resulting list only ignores `plugin.rasp_irc.php`, which is the last line of my `blacklist`, and seems to ignore the other 3 lines above.

I'm now pretty confident this is because my `blacklist` file was created using windows and mounted into the container, and the line breaks are Windows (CR LF) characters instead of Unix (LF), and so they seemed to not work nicely with `grep` and only the last line is taken into account.

I manually created a `blacklist_unix` file while in the container, tried the same command above using that file, and the resulting list properly ignored all 4 plugins in there.

Back to my `blacklist` file, using `Notepad++` I did `Edit->EOL Conversion->Unix (LF)`, saved the change, restarted my container, and now everything seems to work fine, and the `plugins.xml` file does not have any of the `jfreu` plugins.

So that's my particular use case fixed, dunno if it's the same for @UncleEnk.
Ideally grep could work with a CRLF file, but I couldn't quickly find a solution there, and converting the `blacklist` file EOL did the trick.

Thanks again for this project 👍 If that's cool I might submit a few comments/suggestions once I'm done setting things up.

PS: Also I believe that `grep -vFf blacklist` doesn't need the capital `F`, and could just be `grep -vf blacklist`? Doesn't seem to matter though.

**Comment by fanyx** [comment] 2024-10-13 19:25
Oh, that rings some bells!
I believe someone had this exact issue and solution years back but never found a common solution, except for dos2unix'ing their files.
i personally just never had CRLF in my files as i dont use windows.
Should definitly look into a universal way to "grep" over files that use windows encoding.

actually... maybe removing `-F` might just fix it already
Thanks for the find!

**Comment by fanyx** [comment] 2024-10-13 22:54
im honestly this close to just forcing `dos2unix blacklist` before we check the file
can't find any information on how to make `grep` respect CRLF in this case...

**Comment by fanyx** [comment] 2024-10-13 23:28
Alright, should be fixed now
I guess eliminating CR during parsing isn't that hard.
Also, we now use `blacklist.txt` instead of `blacklist` to eliminate that naming convention weirdness.
It's updated in the README, too

If you used `fanyx/tmserver` from docker hub, be sure to use version `:2.2.1`
Let me know, if it works

**Closed as completed** 2024-12-17 23:01 UTC
